apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastapi-explore-pvc
  namespace: fastapi-explore-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
